using Infrastructure.Data;

public static class DbInitializer
{
    public static void Initialize(AppDbContext context)
    {
        context.Database.EnsureCreated();

        if (context.Kpis.Any())
        {
            return;
        }

        var kpis = new Kpi[]
        {
            new Kpi { Name = "Total Sales", Description = "Measures the total revenue generated from sales.", Value = "0", Role = Role.SalesDirector },
            new Kpi { Name = "Sales Growth", Description = "Measures the increase in sales over a specific period.", Value = "0%", Role = Role.SalesDirector },
            new Kpi { Name = "Customer Acquisition Cost (CAC)", Description = "Measures the cost associated with acquiring a new customer.", Value = "$0", Role = Role.SalesDirector },
            new Kpi { Name = "Customer Lifetime Value (CLV)", Description = "Estimates the total revenue expected from a customer over their lifetime.", Value = "$0", Role = Role.SalesDirector },
            new Kpi { Name = "Net Profit Margin", Description = "Measures how much profit a company makes for every dollar of revenue.", Value = "0%", Role = Role.FinancialOfficer },
            new Kpi { Name = "Gross Profit Margin", Description = "Measures the difference between revenue and cost of goods sold.", Value = "0%", Role = Role.FinancialOfficer },
            new Kpi { Name = "Operating Cash Flow", Description = "Measures the cash generated from operations.", Value = "$0", Role = Role.FinancialOfficer },
            new Kpi { Name = "Revenue", Description = "Measures the total income generated by the company.", Value = "$0", Role = Role.CFO },
            new Kpi { Name = "Earnings Before Interest and Taxes (EBIT)", Description = "Measures the company's profitability.", Value = "$0", Role = Role.CFO },
            new Kpi { Name = "Employee Turnover Rate", Description = "Measures the rate at which employees leave the company.", Value = "0%", Role = Role.HR },
            new Kpi { Name = "Employee Satisfaction Index", Description = "Measures employee satisfaction and engagement.", Value = "0%", Role = Role.HR },
            new Kpi { Name = "Time to Hire", Description = "Measures the average time taken to fill a vacant position.", Value = "0 days", Role = Role.HR },
        };

        foreach (var kpi in kpis)
        {
            context.Kpis.Add(kpi);
        }

        context.SaveChanges();
    }
}